<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>$schema</key>
  <string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
  <key>name</key>
  <string>Rivel</string>
  <key>scopeName</key>
  <string>source.rivel</string>
  <key>fileTypes</key>
  <array>
    <string>rivel</string>
  </array>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#code</string>
    </dict>
  </array>
  <key>repository</key>
  <dict>
    <key>code</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#comments</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#strings</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#function-declaration</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#struct-declaration</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#keywords</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numbers</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#types</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#return-type</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#annotated-type</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#calls</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#operators</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#punctuation</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#identifiers</string>
        </dict>
      </array>
    </dict>
    <key>comments</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>comment.line.double-slash.rivel</string>
          <key>begin</key>
          <string>//</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.comment.rivel</string>
            </dict>
          </dict>
          <key>end</key>
          <string>$</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#block-comment</string>
        </dict>
      </array>
    </dict>
    <key>block-comment</key>
    <dict>
      <key>name</key>
      <string>comment.block.rivel</string>
      <key>begin</key>
      <string>/\*</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.comment.begin.rivel</string>
        </dict>
      </dict>
      <key>end</key>
      <string>\*/</string>
      <key>endCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.comment.end.rivel</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#block-comment</string>
        </dict>
      </array>
    </dict>
    <key>strings</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#interpolated-string</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#plain-string</string>
        </dict>
      </array>
    </dict>
    <key>plain-string</key>
    <dict>
      <key>name</key>
      <string>string.quoted.double.rivel</string>
      <key>begin</key>
      <string>"</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.string.begin.rivel</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(")|$</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.string.end.rivel</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#escapes</string>
        </dict>
      </array>
    </dict>
    <key>interpolated-string</key>
    <dict>
      <key>name</key>
      <string>string.quoted.double.interpolated.rivel</string>
      <key>begin</key>
      <string>\bf(")</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.string.begin.rivel</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(")|$</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.string.end.rivel</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#escapes</string>
        </dict>
        <dict>
          <key>name</key>
          <string>constant.character.escape.brace.rivel</string>
          <key>match</key>
          <string>\{\{|\}\}</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#interpolation</string>
        </dict>
        <dict>
          <key>name</key>
          <string>invalid.illegal.unescaped-brace.rivel</string>
          <key>match</key>
          <string>\}</string>
        </dict>
      </array>
    </dict>
    <key>escapes</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>constant.character.escape.rivel</string>
          <key>match</key>
          <string>\\(?:[\\"nrt0]|x[0-9A-Fa-f]{2}|u\{[0-9A-Fa-f]+\})</string>
        </dict>
        <dict>
          <key>name</key>
          <string>invalid.illegal.escape.rivel</string>
          <key>match</key>
          <string>\\.</string>
        </dict>
      </array>
    </dict>
    <key>interpolation</key>
    <dict>
      <key>name</key>
      <string>meta.embedded.expression.rivel</string>
      <key>begin</key>
      <string>\{</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.section.interpolation.begin.rivel</string>
        </dict>
      </dict>
      <key>end</key>
      <string>\}</string>
      <key>endCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.section.interpolation.end.rivel</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#expression-braces</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#code</string>
        </dict>
      </array>
    </dict>
    <key>expression-braces</key>
    <dict>
      <key>name</key>
      <string>meta.braces.rivel</string>
      <key>begin</key>
      <string>\{</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.section.block.begin.rivel</string>
        </dict>
      </dict>
      <key>end</key>
      <string>\}</string>
      <key>endCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.section.block.end.rivel</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#expression-braces</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#code</string>
        </dict>
      </array>
    </dict>
    <key>function-declaration</key>
    <dict>
      <key>name</key>
      <string>meta.function.rivel</string>
      <key>begin</key>
      <string>\b(func)\b(?:[ \t]+([A-Za-z_][A-Za-z0-9_]*))?</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>storage.type.function.rivel</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>entity.name.function.rivel</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(?=[{;])|$</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#comments</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#parameters</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#return-type</string>
        </dict>
        <dict>
          <key>name</key>
          <string>entity.name.function.rivel</string>
          <key>match</key>
          <string>\b[A-Za-z_][A-Za-z0-9_]*\b</string>
        </dict>
      </array>
    </dict>
    <key>parameters</key>
    <dict>
      <key>name</key>
      <string>meta.function.parameters.rivel</string>
      <key>begin</key>
      <string>\(</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.section.parameters.begin.rivel</string>
        </dict>
      </dict>
      <key>end</key>
      <string>\)|(?=[{;])</string>
      <key>endCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.section.parameters.end.rivel</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#comments</string>
        </dict>
        <dict>
          <key>name</key>
          <string>meta.type.annotation.rivel</string>
          <key>begin</key>
          <string>:(?![=])</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.separator.type.rivel</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(?=[,)=;{}])</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#type-expression</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>name</key>
          <string>variable.language.self.rivel</string>
          <key>match</key>
          <string>\bself\b</string>
        </dict>
        <dict>
          <key>name</key>
          <string>variable.parameter.rivel</string>
          <key>match</key>
          <string>\b[A-Za-z_][A-Za-z0-9_]*\b</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#punctuation</string>
        </dict>
      </array>
    </dict>
    <key>struct-declaration</key>
    <dict>
      <key>match</key>
      <string>\b(struct)\b(?:[ \t]+([A-Za-z_][A-Za-z0-9_]*))?</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>storage.type.struct.rivel</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>entity.name.type.struct.rivel</string>
        </dict>
      </dict>
    </dict>
    <key>keywords</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>keyword.control.rivel</string>
          <key>match</key>
          <string>\b(?:if|else|while|for|in|break|continue|return)\b</string>
        </dict>
        <dict>
          <key>name</key>
          <string>keyword.other.reserved.rivel</string>
          <key>match</key>
          <string>\b(?:enum|match|import|as|const|pub|type|is)\b</string>
        </dict>
        <dict>
          <key>name</key>
          <string>variable.language.self.rivel</string>
          <key>match</key>
          <string>\bself\b</string>
        </dict>
        <dict>
          <key>name</key>
          <string>constant.language.boolean.rivel</string>
          <key>match</key>
          <string>\b(?:true|false)\b</string>
        </dict>
        <dict>
          <key>name</key>
          <string>constant.language.null.rivel</string>
          <key>match</key>
          <string>\bnull\b</string>
        </dict>
      </array>
    </dict>
    <key>numbers</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>constant.numeric.integer.hexadecimal.rivel</string>
          <key>match</key>
          <string>\b0x[0-9A-Fa-f_]+\b</string>
        </dict>
        <dict>
          <key>name</key>
          <string>constant.numeric.integer.octal.rivel</string>
          <key>match</key>
          <string>\b0o[0-7_]+\b</string>
        </dict>
        <dict>
          <key>name</key>
          <string>constant.numeric.integer.binary.rivel</string>
          <key>match</key>
          <string>\b0b[01_]+\b</string>
        </dict>
        <dict>
          <key>name</key>
          <string>constant.numeric.float.rivel</string>
          <key>match</key>
          <string>\b[0-9][0-9_]*(?:\.[0-9][0-9_]*(?:[eE][+-]?[0-9]+)?|[eE][+-]?[0-9]+)\b</string>
        </dict>
        <dict>
          <key>name</key>
          <string>constant.numeric.integer.decimal.rivel</string>
          <key>match</key>
          <string>\b[0-9][0-9_]*\b</string>
        </dict>
      </array>
    </dict>
    <key>types</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#list-type</string>
        </dict>
        <dict>
          <key>name</key>
          <string>storage.type.builtin.rivel</string>
          <key>match</key>
          <string>\b(?:int|float|bool|str|list|void)\b</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b([A-Za-z_][A-Za-z0-9_]*)(\?)(?!\?)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.rivel</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.operator.optional.rivel</string>
            </dict>
          </dict>
        </dict>
      </array>
    </dict>
    <key>type-expression</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#comments</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#types</string>
        </dict>
        <dict>
          <key>name</key>
          <string>entity.name.type.rivel</string>
          <key>match</key>
          <string>\b[A-Za-z_][A-Za-z0-9_]*\b</string>
        </dict>
        <dict>
          <key>name</key>
          <string>keyword.operator.optional.rivel</string>
          <key>match</key>
          <string>\?(?!\?)</string>
        </dict>
      </array>
    </dict>
    <key>list-type</key>
    <dict>
      <key>name</key>
      <string>meta.type.list.rivel</string>
      <key>begin</key>
      <string>\b(list)[ \t]*(\[)</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>storage.type.builtin.rivel</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>punctuation.section.type-arguments.begin.rivel</string>
        </dict>
      </dict>
      <key>end</key>
      <string>\]|(?=[;{}()=])</string>
      <key>endCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.section.type-arguments.end.rivel</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#type-expression</string>
        </dict>
      </array>
    </dict>
    <key>return-type</key>
    <dict>
      <key>name</key>
      <string>meta.type.return.rivel</string>
      <key>begin</key>
      <string>-&gt;</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>keyword.operator.arrow.rivel</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(?=[{;=,)}])|$</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#type-expression</string>
        </dict>
      </array>
    </dict>
    <key>annotated-type</key>
    <dict>
      <key>comment</key>
      <string>The = or ; terminator distinguishes declarations from constructor argument labels.</string>
      <key>begin</key>
      <string>(:)(?![=])(?=[ \t]*[A-Za-z_][A-Za-z0-9_]*[ \t]*(?:[=;]))</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.separator.type.rivel</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(?=[=;])|$</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#type-expression</string>
        </dict>
      </array>
    </dict>
    <key>calls</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\.)([ \t]*)(contains|starts_with|ends_with|find|split|join|trim|upper|lower|replace|repeat|append|pop|insert|remove_at|clear|index_of)\b(?=[ \t]*\()</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.accessor.rivel</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>support.function.builtin.rivel</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\.)([ \t]*)([A-Za-z_][A-Za-z0-9_]*)\b(?=[ \t]*\()</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.accessor.rivel</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.rivel</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>name</key>
          <string>support.function.builtin.rivel</string>
          <key>match</key>
          <string>\b(?:print|println|eprintln|len|ord|chr|panic|assert|exit|args|read_file|write_file|read_line|sqrt|abs|min|max|wrapping_add|wrapping_sub|wrapping_mul)\b(?=[ \t]*\()</string>
        </dict>
        <dict>
          <key>name</key>
          <string>entity.name.function.rivel</string>
          <key>match</key>
          <string>\b[A-Za-z_][A-Za-z0-9_]*\b(?=[ \t]*\()</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\.)([ \t]*)([A-Za-z_][A-Za-z0-9_]*)\b</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.accessor.rivel</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>variable.other.member.rivel</string>
            </dict>
          </dict>
        </dict>
      </array>
    </dict>
    <key>operators</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>keyword.operator.range.rivel</string>
          <key>match</key>
          <string>\.\.=?</string>
        </dict>
        <dict>
          <key>name</key>
          <string>keyword.operator.null-coalescing.rivel</string>
          <key>match</key>
          <string>\?\?</string>
        </dict>
        <dict>
          <key>name</key>
          <string>keyword.operator.comparison.rivel</string>
          <key>match</key>
          <string>==|!=|&lt;=|&gt;=</string>
        </dict>
        <dict>
          <key>name</key>
          <string>keyword.operator.assignment.rivel</string>
          <key>match</key>
          <string>:=|[+*/%-]?=</string>
        </dict>
        <dict>
          <key>name</key>
          <string>keyword.operator.logical.rivel</string>
          <key>match</key>
          <string>&amp;&amp;|\|\||!</string>
        </dict>
        <dict>
          <key>name</key>
          <string>keyword.operator.bitwise.rivel</string>
          <key>match</key>
          <string>&lt;&lt;|&gt;&gt;|[&amp;|^~]</string>
        </dict>
        <dict>
          <key>name</key>
          <string>keyword.operator.comparison.rivel</string>
          <key>match</key>
          <string>[&lt;&gt;]</string>
        </dict>
        <dict>
          <key>name</key>
          <string>keyword.operator.arithmetic.rivel</string>
          <key>match</key>
          <string>[+*/%-]</string>
        </dict>
        <dict>
          <key>name</key>
          <string>keyword.operator.optional.rivel</string>
          <key>match</key>
          <string>\?</string>
        </dict>
      </array>
    </dict>
    <key>punctuation</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>punctuation.section.block.begin.rivel</string>
          <key>match</key>
          <string>\{</string>
        </dict>
        <dict>
          <key>name</key>
          <string>punctuation.section.block.end.rivel</string>
          <key>match</key>
          <string>\}</string>
        </dict>
        <dict>
          <key>name</key>
          <string>punctuation.section.group.begin.rivel</string>
          <key>match</key>
          <string>\(</string>
        </dict>
        <dict>
          <key>name</key>
          <string>punctuation.section.group.end.rivel</string>
          <key>match</key>
          <string>\)</string>
        </dict>
        <dict>
          <key>name</key>
          <string>punctuation.section.brackets.begin.rivel</string>
          <key>match</key>
          <string>\[</string>
        </dict>
        <dict>
          <key>name</key>
          <string>punctuation.section.brackets.end.rivel</string>
          <key>match</key>
          <string>\]</string>
        </dict>
        <dict>
          <key>name</key>
          <string>punctuation.separator.comma.rivel</string>
          <key>match</key>
          <string>,</string>
        </dict>
        <dict>
          <key>name</key>
          <string>punctuation.separator.colon.rivel</string>
          <key>match</key>
          <string>:</string>
        </dict>
        <dict>
          <key>name</key>
          <string>punctuation.terminator.statement.rivel</string>
          <key>match</key>
          <string>;</string>
        </dict>
        <dict>
          <key>name</key>
          <string>punctuation.accessor.rivel</string>
          <key>match</key>
          <string>\.</string>
        </dict>
      </array>
    </dict>
    <key>identifiers</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>variable.other.definition.rivel</string>
          <key>match</key>
          <string>\b[A-Za-z_][A-Za-z0-9_]*\b(?=[ \t]*:)</string>
        </dict>
        <dict>
          <key>name</key>
          <string>variable.other.rivel</string>
          <key>match</key>
          <string>\b[A-Za-z_][A-Za-z0-9_]*\b</string>
        </dict>
      </array>
    </dict>
  </dict>
  <key>uuid</key>
  <string>20B58C48-56B4-4142-BBC6-693E7B9D5839</string>
</dict>
</plist>
