const commaList = rule => optional(seq(rule, repeat(seq(',', rule)), optional(',')));
module.exports = grammar({
  name: 'rivel',
  extras: $ => [/\s/, $.line_comment, $.block_comment],
  externals: $ => [$.block_comment],
  word: $ => $.identifier,
  rules: {
    source_file: $ => repeat(choice($.function_declaration, $.struct_declaration, $.variable_declaration)),
    function_declaration: $ => seq('func', field('name', $.identifier), $.parameters, optional(seq('->', field('return_type', $._type))), field('body', $.block)),
    parameters: $ => seq('(', commaList(choice($.parameter, $.self)), ')'),
    parameter: $ => seq(field('name', $.identifier), ':', field('type', $._type)),
    struct_declaration: $ => seq('struct', field('name', $.type_identifier), '{', repeat(choice($.field_declaration, $.function_declaration)), '}'),
    field_declaration: $ => seq(field('name', $.identifier), ':', field('type', $._type), ';'),
    _type: $ => choice($.type_identifier, $.list_type, $.optional_type),
    type_identifier: $ => $.identifier,
    list_type: $ => seq('list', '[', $._type, ']'),
    optional_type: $ => seq(choice($.type_identifier, $.list_type), '?'),
    block: $ => seq('{', repeat($._statement), '}'),
    _statement: $ => choice($.variable_declaration, $.assignment_statement, $.expression_statement,
      $.if_statement, $.while_statement, $.for_statement, $.return_statement, $.break_statement, $.continue_statement, $.block),
    variable_declaration: $ => seq(field('name', $.identifier), choice(':=', seq(':', field('type', $._type), '=')), field('value', $._expression), ';'),
    assignment_statement: $ => seq(field('left', $._expression), choice('=', '+=', '-=', '*=', '/=', '%='), field('right', $._expression), ';'),
    expression_statement: $ => seq($._expression, ';'),
    if_statement: $ => seq('if', field('condition', $._expression), field('consequence', $.block), optional(seq('else', field('alternative', choice($.if_statement, $.block))))),
    while_statement: $ => seq('while', field('condition', $._expression), field('body', $.block)),
    for_statement: $ => seq('for', field('name', $.identifier), 'in', field('iterable', $._expression), field('body', $.block)),
    return_statement: $ => seq('return', optional($._expression), ';'),
    break_statement: _ => seq('break', ';'),
    continue_statement: _ => seq('continue', ';'),
    _expression: $ => choice($.identifier, $.self, $.number, $.boolean, $.null, $.string, $.formatted_string,
      $.list_expression, $.parenthesized_expression, $.unary_expression, $.binary_expression, $.range_expression,
      $.call_expression, $.member_expression, $.index_expression),
    parenthesized_expression: $ => seq('(', $._expression, ')'),
    list_expression: $ => seq('[', commaList($._expression), ']'),
    unary_expression: $ => prec(8, seq(choice('-', '!', '~'), $._expression)),
    binary_expression: $ => choice(...[
      [1, ['??']], [2, ['||']], [3, ['&&']], [4, ['==', '!=', '<', '<=', '>', '>=']],
      [5, ['+', '-', '|', '^']], [6, ['*', '/', '%', '<<', '>>', '&']],
    ].map(([precedence, operators]) => (precedence === 1 ? prec.right : prec.left)(precedence,
      seq(field('left', $._expression), field('operator', operators.length === 1 ? operators[0] : choice(...operators)), field('right', $._expression))))),
    range_expression: $ => prec.left(0, seq($._expression, choice('..', '..='), $._expression)),
    call_expression: $ => prec(9, seq(field('function', $._expression), field('arguments', $.arguments))),
    arguments: $ => seq('(', commaList($.argument), ')'),
    argument: $ => seq(optional(seq(field('label', $.identifier), ':')), $._expression),
    member_expression: $ => prec(9, seq(field('object', $._expression), '.', field('property', $.identifier))),
    index_expression: $ => prec(9, seq(field('object', $._expression), '[', $._expression, ']')),
    self: _ => 'self', boolean: _ => choice('true', 'false'), null: _ => 'null',
    identifier: _ => /[A-Za-z_][A-Za-z0-9_]*/,
    number: _ => token(choice(/0[xX][0-9a-fA-F_]+/, /0[oO][0-7_]+/, /0[bB][01_]+/,
      /[0-9][0-9_]*(\.[0-9][0-9_]*)?([eE][+-]?[0-9][0-9_]*)?/)),
    string: $ => seq('"', repeat(choice($.string_content, $.escape_sequence)), '"'),
    string_content: _ => token.immediate(/[^"\\\r\n]+/),
    escape_sequence: _ => token.immediate(/\\(u\{[0-9a-fA-F]+\}|x[0-9a-fA-F]{2}|[^\r\n])/),
    formatted_string: $ => seq('f"', repeat(choice($.formatted_string_content, $.escape_sequence, $.interpolation)), '"'),
    formatted_string_content: _ => token.immediate(choice(/[^"\\{}\r\n]+/, '{{', '}}')),
    interpolation: $ => seq('{', $._expression, '}'),
    line_comment: _ => token(seq('//', /[^\r\n]*/)),
  },
});
